include:
  - .././apps/test-admin/docker-compose.yml
version: "3"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:debian
    command: sleep infinity
    links:
      - server
